In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [2]:
list_1 = [1, 2, 3, 4, 5]

In [3]:
np_arr_1 = np.array(list_1, dtype=np.int8)

In [4]:
np_arr_1

array([1, 2, 3, 4, 5], dtype=int8)

In [5]:
m_list_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
m_list_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np_m_arr_1 = np.array(m_list_1)

In [7]:
np_m_arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 5, 7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np_m_arr_1.size

9

In [14]:
np_arr_2 = np.array([1, 2, 3, 4, 5, 6])

In [16]:
np_arr_2

array([1, 2, 3, 4, 5, 6])

In [17]:
np_arr_2.dtype

dtype('int32')

In [18]:
np.random.randint(10, 50, 5)

array([16, 43, 24, 23, 17])

In [19]:
np.random.randint(10, 50, size=(2, 3))

array([[32, 21, 14],
       [18, 32, 21]])